name: Test Report for BuildInfoAnalyzers

on:
  workflow_run:
    workflows:
      - 'CI Build and Publish BuildInfoAnalyzers'
      - 'Test BuildInfoAnalyzers'
    types:
      - completed
  workflow_dispatch:
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  test-report:
    runs-on: windows-latest
    steps:
      - name: Download test results artifact
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: ./test-results

      - name: Publish test results summary
        uses: dorny/test-reporter@v2
        with:
          name: BuildInfoAnalyzers Test Results
          path: ./test-results/*.trx
          reporter: dotnet-trx

      - name: Upload test results artifact (again, for convenience)
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./test-results/*.trx
